const foodNames = [ 
    "apple",
    "apricot",
    "avocado",
    "banana",
    "bell pepper",
    "blackberry",
    "blackcurrant",
    "blood orange",
    "blueberry",
    "boysenberry",
    "breadfruit",
    "baby back ribs",
    "ribs",
    "cantaloupe",
    "cherry",
    "chili pepper",
    "clementine",
    "coconut",
    "cranberry",
    "cucumber",
    "currant",
    "damson",
    "date",
    "dragonfruit",
    "durian",
    "puffs",
    "eggplant",
    "elderberry",
    "fig",
    "goji berry",
    "gooseberry",
    "grape",
    "grapefruit",
    "guava",
    "honeydew",
    "huckleberry",
    "jackfruit",
    "jujube",
    "chestnut",
    "kiwi fruit",
    "kumquat",
    "lemon",
    "lime",
    "loquat",
    "lychee",
    "mandarine",
    "mango",
    "mulberry",
    "nectarine",
    "nut",
    "olive",
    "orange",
    "papaya",
    "passionfruit",
    "peach",
    "pear",
    "persimmon",
    "physalis",
    "pineapple",
    "plum",
    "pizza",
    "pomegranate",
    "pomelo",
    "quince",
    "raisin",
    "rambutan",
    "raspberry",
    "redcurrant",
    "satsuma",
    "star fruit",
    "strawberry",
    "tangerine",
    "tomato",
    "watermelon",
    "acorn squash",
    "alfalfa sprout",
    "turkey",
    "ham",
    "bacon",
    "chicken thigh",
    "chicken wing",
    "chicken breast",
    "amaranth",
    "anise",
    "artichoke",
    "arugula",
    "asparagus",
    "aubergine",
    "azuki bean",
    "banana squash",
    "basil",
    "bean sprout",
    "beet",
    "black bean",
    "black-eyed pea",
    "bok choy",
    "borlotti bean",
    "broad beans",
    "beans",
    "broccoflower",
    "broccoli",
    "brussels sprout",
    "butternut squash",
    "cabbage",
    "calabrese",
    "caraway",
    "carrot",
    "cauliflower",
    "cayenne pepper",
    "celeriac",
    "celery",
    "chamomile",
    "chard",
    "chayote",
    "chickpea",
    "chives",
    "cilantro",
    "collard green",
    "corn",
    "corn salad",
    "courgette",
    "cucumber",
    "daikon",
    "delicata",
    "dill",
    "eggplant",
    "endive",
    "fennel",
    "fiddlehead",
    "fern",
    "frisee",
    "garlic",
    "ginger",
    "green bean",
    "green pepper",
    "habanero",
    "herbs and spice",
    "horseradish",
    "hubbard squash",
    "haddock",
    "jalapeno",
    "jerusalem artichoke",
    "jicama",
    "kale",
    "kidney bean",
    "kohlrabi",
    "lavender",
    "leek ",
    "legume",
    "lemon grass",
    "lentils",
    "lettuce",
    "lima bean",
    "mangetout",
    "marjoram",
    "salmon",
    "tuna",
    "tilapia",
    "mung bean",
    "mushroom",
    "mustard green",
    "navy bean",
    "nopale",
    "okra",
    "onion",
    "oregano",
    "paprika",
    "parsley",
    "parsnip",
    "patty pan",
    "pea",
    "pinto bean",
    "tortilla",
    "potato",
    "pumpkin",
    "radicchio",
    "radish",
    "rhubarb",
    "rosemary",
    "runner bean",
    "rutabaga",
    "sage",
    "scallion",
    "shallot",
    "snap pea",
    "soy bean",
    "spaghetti squash",
    "spinach",
    "squash",
    "sweet potato",
    "tabasco sauce",
    "taro",
    "thyme",
    "tubers",
    "turnip",
    "wasabi",
    "water chestnut",
    "watercress",
    "white radish",
    "yam",
    "zucchini",
    "bagel",
    "baguette",
    "boule",
    "brioche",
    "chapati",
    "ciabatta",
    "cornbread",
    "crumpet",
    "epi",
    "ficelle",
    "flatbread",
    "focaccia",
    "fruit bread",
    "banana bread",
    "hamburger bun",
    "lavash",
    "matzoh",
    "muffin",
    "english muffin",
    "naan",
    "paratha",
    "pita",
    "potato bread",
    "pretzel",
    "pumpernickel",
    "roti",
    "rye",
    "scone",
    "soda bread",
    "goat cheese",
    "sourdough",
    "tortilla",
    "baklava",
    "almond butter",
    "sunflower butter",
    "peanut butter",
    "nutella",
    "hazelnut spread",
    "Cheetos",
    "Doritos",
    "potato chips",
    "bomboloni",
    "canelé",
    "cinnamon roll",
    "croissant",
    "fritos",
    "cronut",
    "doughnut",
    "donut",
    "éclair",
    "gulab jamun",
    "mille-feuille",
    "morning bun",
    "pain au chocolat",
    "rugelach",
    "shortcake",
    "stollen",
    "strudel",
    "Aioli",
    "Barbecue sauce",
    "Brown mustard",
    "Chili peppers",
    "Chili sauce",
    "Chili oil",
    "Chimichurri",
    "Chutney",
    "Cocktail sauce",
    "Crushed red pepper",
    "Dijon ketchup",
    "Dijon mustard",
    "Dip",
    "Fish paste",
    "Fish sauce",
    "Fruit preserves",
    "Fry sauce",
    "Guacamole",
    "Honey dill",
    "Horseradish",
    "Hot mustard",
    "Hot sauce",
    "Ketchup",
    "Fruit ketchup",
    "Banana ketchup",
    "Curry ketchup",
    "Kimchi",
    "Mayonnaise",
    "Mignonette sauce",
    "Mushroom ketchup",
    "Mustard",
    "Mustard oil",
    "Nutritional yeast",
    "Olive oil",
    "Pepper jelly",
    "Pesto",
    "Piccalilli",
    "Pickled fruit",
    "Pico de gallo",
    "Mango pickle",
    "Pickled cucumber",
    "Pickled onion",
    "Pickled pepper",
    "Pinđur",
    "Popcorn seasoning",
    "Relish",
    "Salad cream",
    "Salad dressing",
    "Salmoriglio",
    "Salsa",
    "Salt",
    "Salt and pepper",
    "Sauerkraut",
    "Sesame oil",
    "Soy sauce",
    "Sriracha",
    "Steak sauce",
    "Sweet chilli sauce",
    "Syrup",
    "Tartar sauce",
    "Teriyaki sauce",
    "Toum",
    "Vinegar",
    "Black vinegar",
    "Vincotto",
    "Ajwain",
    "Allspice",
    "Amchoor",
    "Camphor",
    "Caraway",
    "Cardamom",
    "Black Cardamom",
    "Celery powder",
    "Celery seed",
    "Cinnamon",
    "Clove",
    "Coriander seed",
    "Cubeb",
    "Cumin",
    "Dill",
    "Dill seed",
    "Fennel",
    "Fenugreek",
    "Galangal",
    "Garlic",
    "Ginger",
    "Horseradish",
    "Juniper berry",
    "Kokum",
    "prawns",
    "Dried Lime",
    "Liquorice",
    "Mace",
    "Mango-ginger",
    "Mastic",
    "Black Mustard",
    "Brown Mustard",
    "White Mustard",
    "Nigella",
    "Nutmeg",
    "Alligator",
    "pepper",
    "Chili Pepper",
    "Cayenne pepper",
    "Paprika",
    "Sansho",
    "Black Peppercorn",
    "Green Peppercorn",
    "White Peppercorn",
    "Pomegranate seed",
    "Poppy seed",
    "Rose",
    "Saffron",
    "Salt",
    "Sassafras",
    "Sesame",
    "Shiso",
    "Tamarind",
    "Tonka bean",
    "Turmeric",
    "Vanilla",
    "Wasabi",
    "Yuzu",
    "Zest",
    "Basil",
    "Holy Basil",
    "Thai Basil",
    "Bay leaf",
    "Indian Bay leaf",
    "Chives",
    "Garlic Chives",
    "Coriander leaf",
    "Cilantro",
    "Coriander",
    "Cress",
    "Curry leaf",
    "Dill",
    "Hemp",
    "Lavender",
    "Lemon balm",
    "Lemon grass",
    "Lemon myrtle",
    "Lemon verbena",
    "Mint",
    "Mugwort",
    "Oregano",
    "Parsley",
    "Rosemary",
    "Sage",
    "Savory",
    "Sansho",
    "Shiso",
    "Sorrel",
    "Thyme",
    "Coffee",
    "Olives",
    "Celery",
    "Tea",
    "Radishes",
    "Mashed potatoes",
    "Boiled potatoes",
    "Fruit",
    "Milk",
    "Chicken salad",
    "Vanilla ice cream",
    "Cocoa",
    "Cheese",
    "Lettuce Salad",
    "Lobster salad",
    "Chocolate",
    "String Beans",
    "Apple Pie",
    "Sardines",
    "Oranges",
    "AMERICAN CHEESE",
    "GREEN PEAS",
    "Assorted cakes",
    "Apollinaris",
    "French fried potatoes",
    "Potato salad",
    "Baked Potatoes",
    "Stewed prunes",
    "Roquefort",
    "Ham",
    "Roast beef",
    "Apples",
    "Chocolate Ice Cream",
    "Stewed tomatoes",
    "Bananas",
    "Sliced Tomatoes",
    "Lima beans",
    "Cucumbers",
    "Ice cream",
    "Edam Cheese",
    "Little Neck clams",
    "Swiss cheese",
    "Tomato Juice",
    "Crackers",
    "Spinach",
    "Cream Cheese",
    "Lettuce",
    "Raisins",
    "Sirloin Steak",
    "Cauliflower",
    "Grapes",
    "BLUE POINTS",
    "Cup Custard",
    "Petits fours",
    "Ripe Olives",
    "Orange",
    "French peas",
    "Fruits",
    "Buttermilk",
    "Tomato Salad",
    "Boiled rice",
    "Kaffee",
    "Iced tea",
    "Corned beef",
    "Cucumber salad",
    "ALMONDS",
    "peanuts",
    "hazelnut",
    "pecan",
    "pistachio",
    "apricot",
    "prunes",
    "walnuts",
    "sunflower seeds",
    "pumpkin seeds",
    "sesame",
    "Dessert",
    "Brussels Sprouts",
    "Romaine Salad",
    "Lyonnaise Potatoes",
    "Marmalade",
    "Dry Toast",
    "Grape fruit",
    "Apple Sauce",
    "Tongue",
    "CAMEMBERT CHEESE",
    "Bread and Butter",
    "Chow chow",
    "Chicken",
    "Cold roast beef",
    "Milk toast",
    "Watermelon",
    "Macaroons",
    "Lettuce and Tomato Salad",
    "Fried Egg Plant",
    "egg",
    "Shrimp Cocktail",
    "Club sandwich",
    "Pears",
    "Chicken Sandwich",
    "Broiled Ham",
    "Baked Apple",
    "Ham Sandwich",
    "STRAWBERRY ICE CREAM",
    "Mutton Chops",
    "Lamb Chops",
    "Corned Beef Hash",
    "Brie",
    "Pastry",
    "Sweet Pickles",
    "Cold Ham",
    "Mince Pie",
    "Coffee Ice Cream",
    "Smoked Salmon",
    "Peach",
    "Fruit salad",
    "Shrimp Salad",
    "Assorted Cakes",
    "Stewed Corn",
    "Asparagus",
    "Tenderloin Steak",
    "Ham and eggs",
    "Scrambled Eggs",
    "Fried Potatoes",
    "Sauterne",
    "Pumpkin Pie",
    "Orange Juice",
    "Fried Eggs",
    "Iced coffee",
    "White Rock",
    "rice pudding",
    "Pear",
    "Boiled eggs",
    "Escarole Salad",
    "Baked Apple with Cream",
    "Oatmeal",
    "Cherrystones",
    "Nuts",
    "Chicory Salad",
    "Salad",
    "Peach Pie",
    "Maraschino",
    "Cafe Parfait",
    "Half Grapefruit",
    "Buttered toast",
    "Green olives",
    "Caviar",
    "Neapolitan ice cream",
    "Figs",
    "edamame",
    "Turkish Coffee",
    "Cream toast",
    "Clam Chowder",
    "Beets",
    "Cantaloupe",
    "Blue Point Oysters",
    "Gorgonzola",
    "New string beans",
    "Bacon and eggs",
    "Stuffed olives",
    "Artichoke",
    "Tongue Sandwich",
    "Oyster cocktail",
    "Ginger Ale",
    "Orange marmalade",
    "SLICED CUCUMBERS",
    "Tomatoes",
    "Grapefruit",
    "Cape Cods",
    "Anchovies",
    "Pickles",
    "Lemonade",
    "Turkey",
    "Gherkins",
    "Cold Slaw",
    "Lamb",
    "Gruyere",
    "Neufchatel",
    "Orange Water Ice",
    "Cocktail Sauce",
    "Toast",
    "Rolls",
    "Oyster Stew",
    "Almonds",
    "Pound cake",
    "Sweet Potatoes",
    "Vanilla Ice Cream",
    "Saratoga Chips",
    "Celery Salad",
    "Clam",
    "Grapefruit Juice",
    "Chicken broth",
    "Gorgonzola Cheese",
    "Waldorf Salad",
    "Sherry",
    "Plums",
    "Pork Chops",
    "Stewed Tomatoes",
    "Fruit Cocktail",
    "Sweet Potatoes",
    "French Coffee",
    "Salted Nuts",
    "Pickled beets",
    "Stewed Prunes",
    "Creamed Spinach",
    "Saute Potatoes",
    "Green Peas",
    "Radis",
    "Steak",
    "Hot Rolls",
    "Cakes",
    "Meringue glacee",
    "Chicken Salad",
    "Cold Corned Beef",
    "Russian Dressing",
    "PORT",
    "Tomato",
    "Mashed Turnips",
    "CLAM BROTH",
    "Green Apple Pie",
    "Cake",
    "FRENCH DRESSING",
    "Cream",
    "pudding",
    "cake",
    "cupcake",
    "Virginia Ham",
    "New Lima Beans",
    "Watercress",
    "Brie cheese",
    "Candied Sweet Potatoes",
    "Little Neck Clams",
    "Sardines",
    "Neufchatel cheese",
    "Green Corn",
    "Amontillado",
    "Watercress Salad",
    "Poached Eggs on Toast",
    "Buckwheat Cakes",
    "Roquefort cheese",
    "Shirred Eggs",
    "Roast chicken",
    "Lady fingers",
    "Squab Chicken",
    "Plover",
    "Macaroni",
    "Strawberries and Cream",
    "Manhattan",
    "Pineapple Juice",
    "Tomato Juice Cocktail",
    "Potatoes au Gratin",
    "Congress Water",
    "Currant Jelly",
    "Graham bread",
    "FRESH FRUIT",
    "Apple",
    "Green Turtle Soup",
    "Lettuce salad",
    "mackerel",
    "Cucumber",
    "Absinthe",
    "Stuffed celery",
    "Dill Pickles",
    "Pineapple",
    "Pickled Walnuts",
    "Mixed Grill",
    "Preserves",
    "Lobster Salad",
    "Martini",
    "Plain Omelette",
    "Tomato Soup",
    "duck",
    "Mutton",
    "Boiled Potatoes",
    "BAKED SWEET POTATOES",
    "New green peas",
    "Ceylon Tea",
    "Clam Juice Cocktail",
    "Vermouth",
    "Biscuit Glace",
    "Broiled Bacon",
    "Hamburger Steak",
    "Hashed browned potatoes",
    "Lobster",
    "Cottage Cheese",
    "Potatoes",
    "ENGLISH BREAKFAST TEA",
    "Fruchte",
    "Honey",
    "peaches",
    "Endive Salad",
    "Strawberries",
    "Clam juice",
    "Queen Olives",
    "Cold tongue",
    "Romaine",
    "Boiled Onions",
    "Filet Mignon",
    "Prime ribs of beef",
    "String beans",
    "French string beans",
    "Prime ribs",
    "Mayonnaise dressing",
    "Custard Pie",
    "Hearts of Celery",
    "French bread",
    "Mixed Pickles",
    "BAKED POTATO",
    "Tomato salad",
    "Oysters",
    "Mayonnaise",
    "Roast Beef Sandwich",
    "Swiss cheese sandwich",
    "Julienne potatoes",
    "Fried oysters",
    "nuggets",
    "chicken nuggets",
    "Mixed ice cream",
    "lamb",
    "breadstick",
    "Danish Pastry",
    "Cucumber Salad",
    "Dates",
    "Oolong Tea",
    "Corn muffins",
    "Stilton Cheese",
    "Anchovy Salad",
    "Spring Lamb",
    "Baked Potato",
    "Cape Cod Oysters",
    "Sliced Fresh Pineapple",
    "Mutton",
    "Raisin cake",
    "Strawberry short cake",
    "Honey Dew Melon",
    "French Fried Potatoes",
    "Poached eggs",
    "Hashed Brown Potatoes",
    "Corn bread",
    "Oyster Bay asparagus",
    "Fromage",
    "Fancy Cakes",
    "Escarole",
    "Horlick's Malted Milk",
    "Pistache ice cream",
    "Clam cocktail",
    "Guava jelly",
    "Boiled Sweet Potatoes",
    "Chilled Tomato Juice",
    "Lima Beans",
    "FRUIT SALAD",
    "bacon",
    "Fruit Cake",
    "Baked apples",
    "Eggs to order",
    "Fried Ham",
    "toasted crackers",
    "American cheese",
    "Mashed Potatoes",
    "Corned beef sandwich",
    "Poussin",
    "Tom Collins",
    "String Beans",
    "Chocolate ice cream",
    "Steak",
    "Stuffed tomatoes",
    "Coffee with Cream",
    "Potato Salad",
    "Vegetable Soup",
    "Clam Fritters",
    "Fresh Shrimp Cocktail",
    "Roquefort Dressing",
    "Preserved figs",
    "Peas",
    "kombucha",
    "cranberry",
    "Stuffed Mangoes",
    "Omelette, plain",
    "Corned Beef and Cabbage",
    "Bermuda potatoes",
    "Whiskey Sour",
    "Sauerkraut Juice",
    "Romaine salad",
    "Hearts of Lettuce",
    "Roast Turkey",
    "Sliced Oranges",
    "Broiled Chicken",
    "Smoked beef",
    "Sliced pineapple",
    "Squash",
    "Boiled Ham",
    "Sherbet",
    "Jam",
    "Strawberry shortcake",
    "Gruyere Cheese",
    "Chicory",
    "Fresh milk",
    "milk",
    "English mutton chop",
    "Potatoes, French fried",
    "Meringue",
    "Iced Tea",
    "Wine Jelly",
    "Stewed rhubarb",
    "Rice",
    "BUTTERED BEETS",
    "Cream of tomato soup",
    "Spaghetti",
    "Stuffed Tomato",
    "Apricots",
    "Plain Omelet",
    "Omelet",
    "Sponge Cake",
    "Potatoes, boiled",
    "Broiled Fresh Mushrooms",
    "Fresh Strawberries",
    "Marmelade",
    "Yorkshire Buck",
    "Canadian Cheese",
    "Salted Almonds",
    "Bluefish",
    "Pie a la Mode",
    "boiled new potatoes",
    "Broccoli",
    "Herring",
    "lemon meringue pie",
    "Beefsteak",
    "Lobster",
    "Daiquiri",
    "Thousand Island Dressing",
    "Potatoes",
    "Spanish omelette",
    "Pistachio Ice Cream",
    "Petit Fours",
    "Seltzer",
    "Grape Fruit",
    "Macaroni",
    "Hot Chocolate",
    "Spaghetti au Gratin",
    "Cherries",
    "GREEN TEA",
    "Creme de Cacao",
    "Potatoes, mashed",
    "Stuffed green peppers",
    "MIXED NUTS",
    "Budweiser",
    "Imported Swiss cheese",
    "Peach Ice Cream",
    "Sliced Orange",
    "Rice Cakes",
    "French rolls",
    "bluefish",
    "Bouillon",
    "Shredded Wheat",
    "Tangerines",
    "Apricot",
    "Boston Brown Bread",
    "Grapefruit Supreme",
    "Pickled onions",
    "Hearts of lettuce salad",
    "ORANGE PEKOE",
    "pekoe tea",
    "American",
    "Milk Toast",
    "Iced Coffee",
    "rhubarb pie",
    "Sliced Bananas",
    "Cheese Sandwich",
    "Rice Pudding",
    "Spinach with egg",
    "Partridge",
    "Pork and beans",
    "Chutney",
    "orange sherbet",
    "Chocolate Parfait",
    "Lobster cocktail",
    "Chow Chow",
    "Swiss",
    "apple",
    "Cranberry Sauce",
    "Chicken consomme",
    "Pancake",
    "waffles",
    "toast",
    "french toast",
    "Tapioca",
    "APRICOT PIE",
    "Chartreuse, Yellow",
    "American Cheese",
    "Club Sandwich",
    "Roast Lamb",
    "Gin Fizz",
    "Cheese Cake",
    "Cauliflower au Gratin",
    "Clam Broth",
    "Chocolate Eclairs",
    "Philadelphia Cream Cheese",
    "coconut pie",
    "Cherry Pie",
    "Pheasant",
    "Wheat Cakes",
    "PRUNES",
    "Ham Omelet",
    "Assorted cheese",
    "Cheddar Cheese",
    "Codfish Cakes",
    "Soda",
    "American Cheese Sandwich",
    "Fresh Vegetable Salad",
    "Raspberry sherbet",
    "Green peas",
    "Apple pie",
    "Martini Cocktail",
    "Boston baked beans",
    "Fried Oysters",
    "Strawberry Ice Cream",
    "Dutch cheese",
    "Halibut steak",
    "MILK, PER GLASS",
    "Eggs, fried",
    "Sliced Peaches",
    "Celeri",
    "Preserved Peaches",
    "Fruit in Season",
    "Roast beef",
    "RUM",
    "Baked Beans",
    "Bluepoints",
    "Potatoes Lyonnaise",
    "Cervelat",
    "Caviar, Special Importation",
    "Fried hominy",
    "Lemon Sherbet",
    "Dandelion Salad",
    "Lemon Soda",
    "Combination Salad",
    "Extra Special Heavy Cream",
    "Breakfast Bacon",
    "Egg plant",
    "Omelet, plain",
    "Rudesheimer",
    "Rye Bread",
    "Manhattan Cocktail",
    "Fresh String Beans",
    "Fried Clams",
    "cole slaw",
    "Chocolate eclair",
    "Sardellen",
    "Cheese and Crackers",
    "Corn fritters",
    "French asparagus",
    "Spanish olives",
    "Potatoes, baked",
    "Potato Croquettes",
    "Caramel custard",
    "Crabmeat Cocktail",
    "Crab flake cocktail",
    "Strawberry ice cream",
    "CHAMPAGNE",
    "Clam Stew ",
    "Asparagus Tips",
    "Chicken Salad Sandwich",
    "Mixed Green Salad",
    "Watercress salad",
    "Fried Oyster Crabs",
    "Potatoes hashed in cream",
    "Chef's Salad",
    "Baked Alaska",
    "Sliced Chicken",
    "Apple Juice",
    "Strawberries",
    "Petits Fours",
    "Camembert cheese",
    "Celery salad",
    "Russian caviar",
    "fresh strawberry ice cream",
    "Cold Chicken",
    "Mixed Ice Cream",
    "Champagne Cocktail",
    "Cocktail",
    "Grape Nuts",
    "BLUEBERRY PIE",
    "Eclair",
    "Preserved Skinless Figs",
    "Supreme of Fruit, Astor",
    "Ice Cream",
    "Stewed pears",
    "Onion Soup au gratin",
    "Cup custard",
    "Soft Shell Crabs",
    "Crackers and Milk",
    "Butter",
    "Assorted Fruit",
    "Lettuce and Tomato",
    "Boiled Rice",
    "Raspberries",
    "Caviar sandwich",
    "Cold turkey",
    "Pot of Tea",
    "Spaghetti Italienne",
    "Heart of Lettuce Salad",
    "Oyster Patties",
    "French Toast",
    "Old Fashioned",
    "Melon",
    "Alligator Pear Salad",
    "Anchovis",
    "MUFFINS",
    "Stuffed Olives",
    "Side Car",
    "Eggs, boiled",
    "Eggs, Scrambled",
    "Peach Short Cake",
    "Nuts and Raisins",
    "Fried Soft Shell Crabs",
    "Clams",
    "Stewed potatoes",
    "Potato",
    "compot",
    "Marinated Herring",
    "Coffee, Pot",
    "Salami",
    "Chicken okra soup",
    "Bacardi Cocktail",
    "California Orange",
    "Apple sauce",
    "Neapolitan Ice Cream",
    "Endive salad",
    "Beef",
    "Cognac",
    "Neapolitan",
    "Figs in syrup",
    "Lady Fingers",
    "Stuffed Figs and Dates",
    "Oatmeal Porridge",
    "Mixed Salad",
    "Cheese Omelette",
    "Strawberry jam",
    "Macaroni au Gratin",
    "Fried Scallops",
    "Nesselrode pudding",
    "Sliced Bananas and Cream",
    "Irish stew",
    "Cafe Turc",
    "Oyster Fry",
    "Fancy Ice Cream",
    "Vienna Bread",
    "Grape Juice",
    "Escarole salad",
    "Brawn",
    "Trout",
    "Fried onions",
    "Fresh strawberries and cream",
    "Bologna Sausage",
    "Assorted Nuts",
    "Chicken sandwich",
    "Rockaways",
    "Biscuits",
    "Fried Bacon",
    "Blackberries",
    "Coca Cola",
    "Salted almonds",
    "Young Onions",
    "Onions",
    "Club Soda",
    "Ribs of beef ",
    "Roast Lamb, Mint Sauce",
    "GRAHAM ROLLS",
    "Cream cheese",
    "Squab Chicken (half)",
    "Old Tom Gin",
    "Shrimp",
    "Steamed Rice",
    "Coffee ice cream",
    "Whitebait",
    "Crab Meat salad",
    "India Relish",
    "Rice and milk",
    "Lobster, Newburg",
    "Fresh asparagus",
    "Venison",
    "Lettuce and Tomato Sandwich",
    "Ham sandwich",
    "Curried Chicken with Rice",
    "Gin Rickey",
    "Cocktails",
    "Head Cheese",
    "Cold Lamb",
    "Hot mince pie",
    "Assorted Fresh Fruit",
    "Cold rice pudding",
    "Sirloin steak",
    "Chicory salad",
    "Plain Lemonade",
    "COFFEE",
    "ROAST TURKEY, CRANBERRY SAUCE",
    "Sherry Flip",
    "Mangoes",
    "Raspberry jam",
    "Fresh Fruit Cocktail",
    "Fried Sweet Potatoes",
    "Fish cakes",
    "Lettuce and Tomatoes",
    "Lamb, mint sauce",
    "Guinness' Stout",
    "Rolls and butter",
    "Spinach with Egg",
    "Fried smelts",
    "Oyster stew",
    "Maple Syrup",
    "Smoked Beef Tongue",
    "TUTTI FRUTTI ICE CREAM",
    "Strawberries with cream",
    "Corn Cakes",
    "Ham omelette",
    "Waffles",
    "Spanish omelet",
    "Glass of milk",
    "Sliced Bananas with Cream",
    "Brandy",
    "Canape of Caviar",
    "Eggs, shirred",
    "Salmon Salad",
    "Broiled Squab",
    "Oyster Bay Asparagus",
    "Crab Salad",
    "Pickled Oysters",
    "Alligator Pear",
    "Caviar Canape",
    "Prune Juice",
    "Tongue sandwich",
    "Pistache Ice Cream",
    "New asparagus",
    "Tea",
    "Potatoes Julienne",
    "Gumbo",
    "Malted Milk",
    "Chicken Soup",
    "Beef consomme",
    "Corn Flakes",
    "Crabflake Cocktail",
    "Hors D'oeuvres",
    "Ham and Eggs",
    "Ribs of prime beef",
    "Beef tongue",
    "Cream, per glass",
    "Sauerkraut",
    "Stewed Oysters",
    "AMERICAN COFFEE",
    "liver and bacon",
    "Fresh mushrooms",
    "lemon pie",
    "Pie",
    "Chocolate Sundae",
    "Dill Pickle",
    "Port du Salut cheese",
    "Pink Lady",
    "Bacon and Eggs",
    "Country Sausage",
    "Potatoes, Saratoga",
    "Turnips",
    "Graham Wafers",
    "Broiled oysters",
    "Stewed Strawberries",
    "Baked apples with cream",
    "Liver Sausage",
    "Boston Cream Pie",
    "Spring Onions",
    "Lamb Chop",
    "Tomato Broth",
    "Roast Beef",
    "Roast Potatoes",
    "Fruits in Season",
    "Eclairs",
    "Spring chicken",
    "Cauliflower, Polonaise",
    "Hashed Browned Potatoes",
    "Corn Fritters",
    "Caviar",
    "Clam broth",
    "Lemon ice cream",
    "Crullers",
    "Cacao",
    "Jamaica Rum",
    "Potatoes, Fried",
    "Chocolate Layer Cake",
    "Apple Fritters",
    "French Sardines",
    "Fresh Fruit Cup",
    "Long Island Duckling",
    "Cream Toast",
    "Hamburg steak",
    "French vanilla ice cream",
    "Jelly",
    "Combination salad",
    "Ginger",
    "Pumpkin pie",
    "OLIVES",
    "Sliced Cucumbers",
    "Old Tom",
    "Strained honey",
    "Tomato Omelette",
    "Vegetable Salad",
    "Pineapple Cheese",
    "Blackberry Brandy",
    "anchovies",
    "artichoke",
    "bacon",
    "breakfast bacon",
    "Canadian bacon",
    "cheese",
    "chicken",
    "chili peppers",
    "feta",
    "garlic",
    "green peppers",
    "grilled onions",
    "ground beef",
    "ham",
    "hot sauce",
    "meatballs",
    "mushrooms",
    "olives",
    "onions",
    "pepperoni",
    "pineapple",
    "sausage",
    "spinach",
    "sun-dried tomato",
    "tomatoes",
    "breakfast sausage",
    "bologna",
    "chorizo",
    "bread",
    "wheat bread",
    "white bread"
];

export default foodNames;